# Generated by Django 4.2.1 on 2023-05-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signin',
            old_name='first_name',
            new_name='Fname',
        ),
        migrations.RenameField(
            model_name='signin',
            old_name='last_name',
            new_name='Lname',
        ),
        migrations.RenameField(
            model_name='signin',
            old_name='birthdate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='signin',
            old_name='department',
            new_name='dep',
        ),
    ]
