# Generated by Django 4.2.1 on 2023-05-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_first_name_signin_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signin',
            name='date',
        ),
        migrations.AddField(
            model_name='signin',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
    ]
