# Generated by Django 4.2.1 on 2023-05-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_signin_date_signin_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3),
        ),
    ]
