# Generated by Django 4.2.1 on 2023-05-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_signin_gpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signin',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='signin',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='signin',
            name='level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1),
        ),
    ]
