# Generated by Django 4.2.1 on 2023-05-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_signin_date_of_birth_signin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
