# Generated by Django 4.2.1 on 2023-05-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_signin_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='signin',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default=None, max_length=10, null=True),
        ),
    ]
