# Generated by Django 4.2.1 on 2023-05-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_signin_level_alter_signin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='dep',
            field=models.CharField(choices=[('General', 'General'), ('CS', 'CS'), ('IT', 'IT'), ('DS', 'DS'), ('IS', 'IS'), ('AI', 'AI')], default=None, max_length=50, null=True),
        ),
    ]
