# Generated by Django 4.2.1 on 2023-05-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_signin_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='signin',
            name='phone',
            field=models.CharField(default=None, max_length=11, null=True),
        ),
    ]
