# Generated by Django 4.2.1 on 2023-05-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=11)),
                ('gender', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
