# Generated by Django 4.2.1 on 2023-05-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_department_alter_student_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='birthdate',
            new_name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
